management:
  server:
    port: 8081
  context-path: /actuator
  
server:
  port: 8080
  
keycloak:
  enabled: true
  realm: demo
  auth-server-url: https://sso-sso.apps.ehealth.rht-labs.com/auth
  ssl-required: all
  confidential-port: 443
  resource: springboot-rest
  security-constraints[0]:
    authRoles[0]: user
    securityCollections[0]:
      patterns[0]: /*

